// Generates build assets that are checked in:
//   1. wwwroot/fonts/*.woff2      — copied from @fontsource-variable
//   2. Pages/Shared/_IconSprite.cshtml — inline SVG sprite from bootstrap-icons
//
// Run via `npm run build:assets` (included in `npm run build`).

import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NM = join(ROOT, 'node_modules');

// --- Fonts -------------------------------------------------------------------
// Only latin + latin-ext are shipped. latin-ext carries the Czech diacritics
// (ě š č ř ž ů ď ť ň, U+0100-02BA) and is fetched only when a page needs them.
const FONTS = ['inter', 'source-serif-4', 'jetbrains-mono'];
const SUBSETS = ['latin', 'latin-ext'];

const fontDir = join(ROOT, 'wwwroot', 'fonts');
mkdirSync(fontDir, { recursive: true });

let copied = 0;
for (const family of FONTS) {
	for (const subset of SUBSETS) {
		const file = `${family}-${subset}-wght-normal.woff2`;
		const src = join(NM, '@fontsource-variable', family, 'files', file);
		if (!existsSync(src)) {
			console.error(`MISSING FONT: ${src}`);
			process.exit(1);
		}
		copyFileSync(src, join(fontDir, file));
		copied++;
	}
}
console.log(`fonts: copied ${copied} files`);

// --- Icon sprite -------------------------------------------------------------
// Inlined rather than referenced as an external file because Safari's support
// for external <use href="sprite.svg#id"> is unreliable.
const ICONS = [
	'github', 'twitter-x', 'youtube', 'facebook', 'code-slash',
	'calendar3', 'arrow-left', 'arrow-up', 'inbox',
	'circle-half', 'sun', 'moon-stars',
	'play-circle', 'play-fill', 'file-earmark-pdf',
	'list', 'link-45deg', 'check-lg', 'image', 'rss', 'tag', 'folder2-open',
];

const iconDir = join(NM, 'bootstrap-icons', 'icons');
const symbols = [];

for (const name of ICONS) {
	let raw;
	try {
		raw = readFileSync(join(iconDir, `${name}.svg`), 'utf8');
	} catch {
		console.error(`MISSING ICON: ${name}`);
		process.exit(1);
	}
	const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 16 16';
	const inner = raw
		.replace(/^[\s\S]*?<svg[^>]*>/, '')
		.replace(/<\/svg>\s*$/, '')
		.replace(/<!--[\s\S]*?-->/g, '')
		.trim();
	if (!inner) {
		console.error(`EMPTY ICON: ${name}`);
		process.exit(1);
	}
	symbols.push(`\t<symbol id="i-${name}" viewBox="${viewBox}">${inner}</symbol>`);
}

const sprite = `@*
	AUTO-GENERATED by Scripts/build-assets.mjs from the bootstrap-icons package.
	Do not hand-edit — add the icon name to the ICONS array and re-run
	\`npm run build:assets\` instead.
*@
<svg xmlns="http://www.w3.org/2000/svg" class="icon-sprite" aria-hidden="true" focusable="false">
${symbols.join('\n')}
</svg>
`;

writeFileSync(join(ROOT, 'Pages', 'Shared', '_IconSprite.cshtml'), sprite, 'utf8');
console.log(`icons: wrote ${symbols.length} symbols (${(Buffer.byteLength(sprite) / 1024).toFixed(1)} KB)`);
