global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.UI.Xaml.Markup;
global using MZikmund.App;
global using MZikmund.DataContracts;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
